# Generated by Django 4.0.2 on 2022-02-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='venue name')),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=19)),
                ('phone', models.CharField(max_length=28, verbose_name='Contact Phone')),
                ('web', models.URLField(verbose_name='Website Address')),
                ('email_a', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event name')),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('manager', models.CharField(max_length=60)),
                ('decription', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, to='pages.MyClubUser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.venue')),
            ],
        ),
    ]
